// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {app} from '../models';
import {config} from '../models';

export function AbortCurrentTurn(arg1:string,arg2:string):Promise<void>;

export function AddCronJob(arg1:store.CronJob):Promise<void>;

export function AddSkillPath(arg1:string,arg2:string):Promise<void>;

export function CreateMemoryFile(arg1:string):Promise<string>;

export function DeleteChannelConfig(arg1:string):Promise<void>;

export function DeleteCronJob(arg1:string):Promise<void>;

export function DeleteMemoryFile(arg1:string):Promise<void>;

export function DeleteVaultEntry(arg1:string):Promise<void>;

export function EmitChannelStatus(arg1:string,arg2:string):Promise<void>;

export function GetAgentSkills(arg1:string):Promise<Array<app.SkillInfo>>;

export function GetAllSkills():Promise<Array<app.SkillInfo>>;

export function GetChannels():Promise<Array<app.ChannelInfo>>;

export function GetChatSessions(arg1:string):Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetConfigRaw():Promise<Record<string, string>>;

export function GetCronJobHistory(arg1:string,arg2:number):Promise<Array<store.CronJobHistory>>;

export function GetCronJobHistoryAll(arg1:number):Promise<Array<store.CronJobHistory>>;

export function GetFeishuConfig():Promise<Record<string, string>>;

export function GetHistory(arg1:string,arg2:string):Promise<Array<Record<string, string>>>;

export function GetMemoryDir():Promise<string>;

export function GetMemoryFileContent(arg1:string):Promise<string>;

export function GetModels(arg1:string):Promise<Array<string>>;

export function GetProviders():Promise<Array<app.ProviderInfo>>;

export function GetSessions():Promise<Array<app.SessionInfo>>;

export function GetSkillContent(arg1:string):Promise<string>;

export function GetToolExecutions(arg1:string,arg2:string):Promise<Array<app.ToolExecutionInfo>>;

export function GetVault():Promise<Array<store.VaultEntry>>;

export function GetVersion():Promise<string>;

export function GetWebhookBaseURL():Promise<string>;

export function GetWhatsAppQR():Promise<string>;

export function GetWhatsAppStatus():Promise<string>;

export function IsFirstRun():Promise<boolean>;

export function ListCronJobs():Promise<Array<store.CronJob>>;

export function ListMemoryFiles():Promise<Array<app.MemoryFile>>;

export function LogoutWhatsApp():Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function ReadCanvasFile(arg1:string):Promise<string>;

export function RemoveSkillPath(arg1:string,arg2:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveChannelConfig(arg1:config.AgentConfig):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveConfigRaw(arg1:string):Promise<void>;

export function SaveFeishuConfig(arg1:string,arg2:string):Promise<void>;

export function SaveMemoryFileContent(arg1:string,arg2:string):Promise<void>;

export function SearchMemory(arg1:string,arg2:number):Promise<Array<app.MemorySearchResult>>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetVaultEntry(arg1:string,arg2:string):Promise<void>;

export function StartOAuthLogin(arg1:string):Promise<void>;

export function SyncMemory():Promise<void>;

export function TestChannelConnection(arg1:string):Promise<boolean>;

export function TestProviderConnection(arg1:string):Promise<boolean>;

export function ToggleCronJob(arg1:string,arg2:boolean):Promise<void>;

export function TriggerCronJob(arg1:string):Promise<void>;

export function UpdateCronJob(arg1:store.CronJob):Promise<void>;

export function WriteCanvasFile(arg1:string,arg2:string):Promise<void>;
