package types

import (
	"encoding/json"
	"fmt"
	"time"
)

// StopReason indicates why the assistant stopped generating.
type StopReason string

const (
	StopReasonStop    StopReason = "stop"
	StopReasonLength  StopReason = "length"
	StopReasonToolUse StopReason = "toolUse"
	StopReasonError   StopReason = "error"
	StopReasonAborted StopReason = "aborted"
)

// UsageCost holds the monetary cost breakdown for a single LLM call.
type UsageCost struct {
	Input      float64 `json:"input"`
	Output     float64 `json:"output"`
	CacheRead  float64 `json:"cacheRead"`
	CacheWrite float64 `json:"cacheWrite"`
	Total      float64 `json:"total"`
}

// Usage holds token counts and cost information for a single LLM call.
type Usage struct {
	Input      int       `json:"input"`
	Output     int       `json:"output"`
	CacheRead  int       `json:"cacheRead"`
	CacheWrite int       `json:"cacheWrite"`
	Total      int       `json:"total"`
	Cost       UsageCost `json:"cost"`
}

// Message is implemented by all message types in a conversation.
type Message interface {
	MessageRole() string
}

// rawContentBlock is used internally for JSON unmarshaling of content arrays.
type rawContentBlock struct {
	Type string `json:"type"`
}

// unmarshalContentBlocks parses a JSON array of polymorphic content blocks.
func unmarshalContentBlocks(data json.RawMessage) ([]ContentBlock, error) {
	var raws []json.RawMessage
	if err := json.Unmarshal(data, &raws); err != nil {
		return nil, err
	}
	blocks := make([]ContentBlock, 0, len(raws))
	for _, raw := range raws {
		var r rawContentBlock
		if err := json.Unmarshal(raw, &r); err != nil {
			return nil, err
		}
		var block ContentBlock
		switch r.Type {
		case ContentTypeText:
			v := &TextContent{}
			if err := json.Unmarshal(raw, v); err != nil {
				return nil, err
			}
			block = v
		case ContentTypeImage:
			v := &ImageContent{}
			if err := json.Unmarshal(raw, v); err != nil {
				return nil, err
			}
			block = v
		case ContentTypeAudio:
			v := &AudioContent{}
			if err := json.Unmarshal(raw, v); err != nil {
				return nil, err
			}
			block = v
		case ContentTypeToolCall:
			v := &ToolCall{}
			if err := json.Unmarshal(raw, v); err != nil {
				return nil, err
			}
			block = v
		case ContentTypeThinking:
			v := &ThinkingContent{}
			if err := json.Unmarshal(raw, v); err != nil {
				return nil, err
			}
			block = v
		default:
			return nil, fmt.Errorf("unknown content block type: %q", r.Type)
		}
		blocks = append(blocks, block)
	}
	return blocks, nil
}

// UserMessage is a message authored by the human user.
type UserMessage struct {
	Role      string         `json:"role"`
	Content   []ContentBlock `json:"content"`
	Timestamp int64          `json:"timestamp"`
}

// MessageRole returns the role identifier for UserMessage.
func (m *UserMessage) MessageRole() string { return "user" }

// MarshalJSON serializes UserMessage to JSON.
func (m UserMessage) MarshalJSON() ([]byte, error) {
	type Alias struct {
		Role      string           `json:"role"`
		Content   []ContentBlock   `json:"content"`
		Timestamp int64            `json:"timestamp"`
	}
	return json.Marshal(Alias(m))
}

// UnmarshalJSON deserializes UserMessage from JSON, dispatching content blocks by type.
func (m *UserMessage) UnmarshalJSON(data []byte) error {
	var raw struct {
		Role      string          `json:"role"`
		Content   json.RawMessage `json:"content"`
		Timestamp int64           `json:"timestamp"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	m.Role = raw.Role
	m.Timestamp = raw.Timestamp
	if raw.Content != nil {
		blocks, err := unmarshalContentBlocks(raw.Content)
		if err != nil {
			return err
		}
		m.Content = blocks
	}
	return nil
}

// NewUserMessage constructs a UserMessage with the current timestamp.
func NewUserMessage(content ...ContentBlock) *UserMessage {
	return &UserMessage{
		Role:      "user",
		Content:   content,
		Timestamp: time.Now().UnixMilli(),
	}
}

// AssistantMessage is a message generated by the LLM assistant.
type AssistantMessage struct {
	Role         string         `json:"role"`
	Content      []ContentBlock `json:"content"`
	API          string         `json:"api"`
	Provider     string         `json:"provider"`
	Model        string         `json:"model"`
	Usage        Usage          `json:"usage"`
	StopReason   StopReason     `json:"stopReason"`
	ErrorMessage string         `json:"errorMessage,omitempty"`
	Timestamp    int64          `json:"timestamp"`
}

// MessageRole returns the role identifier for AssistantMessage.
func (m *AssistantMessage) MessageRole() string { return "assistant" }

// MarshalJSON serializes AssistantMessage to JSON.
func (m AssistantMessage) MarshalJSON() ([]byte, error) {
	type Alias struct {
		Role         string         `json:"role"`
		Content      []ContentBlock `json:"content"`
		API          string         `json:"api"`
		Provider     string         `json:"provider"`
		Model        string         `json:"model"`
		Usage        Usage          `json:"usage"`
		StopReason   StopReason     `json:"stopReason"`
		ErrorMessage string         `json:"errorMessage,omitempty"`
		Timestamp    int64          `json:"timestamp"`
	}
	return json.Marshal(Alias(m))
}

// UnmarshalJSON deserializes AssistantMessage from JSON, dispatching content blocks by type.
func (m *AssistantMessage) UnmarshalJSON(data []byte) error {
	var raw struct {
		Role         string          `json:"role"`
		Content      json.RawMessage `json:"content"`
		API          string          `json:"api"`
		Provider     string          `json:"provider"`
		Model        string          `json:"model"`
		Usage        Usage           `json:"usage"`
		StopReason   StopReason      `json:"stopReason"`
		ErrorMessage string          `json:"errorMessage,omitempty"`
		Timestamp    int64           `json:"timestamp"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	m.Role = raw.Role
	m.API = raw.API
	m.Provider = raw.Provider
	m.Model = raw.Model
	m.Usage = raw.Usage
	m.StopReason = raw.StopReason
	m.ErrorMessage = raw.ErrorMessage
	m.Timestamp = raw.Timestamp
	if raw.Content != nil {
		blocks, err := unmarshalContentBlocks(raw.Content)
		if err != nil {
			return err
		}
		m.Content = blocks
	}
	return nil
}

// ToolResultMessage carries the result of a tool invocation back to the LLM.
type ToolResultMessage struct {
	Role       string         `json:"role"`
	ToolCallID string         `json:"toolCallId"`
	ToolName   string         `json:"toolName"`
	Content    []ContentBlock `json:"content"`
	Details    any            `json:"details,omitempty"`
	IsError    bool           `json:"isError"`
	Timestamp  int64          `json:"timestamp"`
}

// MessageRole returns the role identifier for ToolResultMessage.
func (m *ToolResultMessage) MessageRole() string { return "tool" }

// MarshalJSON serializes ToolResultMessage to JSON.
func (m ToolResultMessage) MarshalJSON() ([]byte, error) {
	type Alias struct {
		Role       string         `json:"role"`
		ToolCallID string         `json:"toolCallId"`
		ToolName   string         `json:"toolName"`
		Content    []ContentBlock `json:"content"`
		Details    any            `json:"details,omitempty"`
		IsError    bool           `json:"isError"`
		Timestamp  int64          `json:"timestamp"`
	}
	return json.Marshal(Alias(m))
}

// UnmarshalJSON deserializes ToolResultMessage from JSON, dispatching content blocks by type.
func (m *ToolResultMessage) UnmarshalJSON(data []byte) error {
	var raw struct {
		Role       string          `json:"role"`
		ToolCallID string          `json:"toolCallId"`
		ToolName   string          `json:"toolName"`
		Content    json.RawMessage `json:"content"`
		Details    any             `json:"details,omitempty"`
		IsError    bool            `json:"isError"`
		Timestamp  int64           `json:"timestamp"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	m.Role = raw.Role
	m.ToolCallID = raw.ToolCallID
	m.ToolName = raw.ToolName
	m.Details = raw.Details
	m.IsError = raw.IsError
	m.Timestamp = raw.Timestamp
	if raw.Content != nil {
		blocks, err := unmarshalContentBlocks(raw.Content)
		if err != nil {
			return err
		}
		m.Content = blocks
	}
	return nil
}
