// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortCurrentTurn(arg1, arg2) {
  return window['go']['app']['App']['AbortCurrentTurn'](arg1, arg2);
}

export function AddCronJob(arg1) {
  return window['go']['app']['App']['AddCronJob'](arg1);
}

export function AddSkillPath(arg1, arg2) {
  return window['go']['app']['App']['AddSkillPath'](arg1, arg2);
}

export function CreateMemoryFile(arg1) {
  return window['go']['app']['App']['CreateMemoryFile'](arg1);
}

export function DeleteChannelConfig(arg1) {
  return window['go']['app']['App']['DeleteChannelConfig'](arg1);
}

export function DeleteCronJob(arg1) {
  return window['go']['app']['App']['DeleteCronJob'](arg1);
}

export function DeleteMemoryFile(arg1) {
  return window['go']['app']['App']['DeleteMemoryFile'](arg1);
}

export function DeleteVaultEntry(arg1) {
  return window['go']['app']['App']['DeleteVaultEntry'](arg1);
}

export function EmitChannelStatus(arg1, arg2) {
  return window['go']['app']['App']['EmitChannelStatus'](arg1, arg2);
}

export function GetAgentSkills(arg1) {
  return window['go']['app']['App']['GetAgentSkills'](arg1);
}

export function GetAllSkills() {
  return window['go']['app']['App']['GetAllSkills']();
}

export function GetChannels() {
  return window['go']['app']['App']['GetChannels']();
}

export function GetChatSessions(arg1) {
  return window['go']['app']['App']['GetChatSessions'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConfigRaw() {
  return window['go']['app']['App']['GetConfigRaw']();
}

export function GetCronJobHistory(arg1, arg2) {
  return window['go']['app']['App']['GetCronJobHistory'](arg1, arg2);
}

export function GetCronJobHistoryAll(arg1) {
  return window['go']['app']['App']['GetCronJobHistoryAll'](arg1);
}

export function GetFeishuConfig() {
  return window['go']['app']['App']['GetFeishuConfig']();
}

export function GetHistory(arg1, arg2) {
  return window['go']['app']['App']['GetHistory'](arg1, arg2);
}

export function GetMemoryDir() {
  return window['go']['app']['App']['GetMemoryDir']();
}

export function GetMemoryFileContent(arg1) {
  return window['go']['app']['App']['GetMemoryFileContent'](arg1);
}

export function GetModels(arg1) {
  return window['go']['app']['App']['GetModels'](arg1);
}

export function GetProviders() {
  return window['go']['app']['App']['GetProviders']();
}

export function GetSessions() {
  return window['go']['app']['App']['GetSessions']();
}

export function GetSkillContent(arg1) {
  return window['go']['app']['App']['GetSkillContent'](arg1);
}

export function GetToolExecutions(arg1, arg2) {
  return window['go']['app']['App']['GetToolExecutions'](arg1, arg2);
}

export function GetVault() {
  return window['go']['app']['App']['GetVault']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function GetWebhookBaseURL() {
  return window['go']['app']['App']['GetWebhookBaseURL']();
}

export function GetWhatsAppQR() {
  return window['go']['app']['App']['GetWhatsAppQR']();
}

export function GetWhatsAppStatus() {
  return window['go']['app']['App']['GetWhatsAppStatus']();
}

export function IsFirstRun() {
  return window['go']['app']['App']['IsFirstRun']();
}

export function ListCronJobs() {
  return window['go']['app']['App']['ListCronJobs']();
}

export function ListMemoryFiles() {
  return window['go']['app']['App']['ListMemoryFiles']();
}

export function LogoutWhatsApp() {
  return window['go']['app']['App']['LogoutWhatsApp']();
}

export function OpenLogsFolder() {
  return window['go']['app']['App']['OpenLogsFolder']();
}

export function ReadCanvasFile(arg1) {
  return window['go']['app']['App']['ReadCanvasFile'](arg1);
}

export function RemoveSkillPath(arg1, arg2) {
  return window['go']['app']['App']['RemoveSkillPath'](arg1, arg2);
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['app']['App']['SaveAPIKey'](arg1, arg2);
}

export function SaveChannelConfig(arg1) {
  return window['go']['app']['App']['SaveChannelConfig'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveConfigRaw(arg1) {
  return window['go']['app']['App']['SaveConfigRaw'](arg1);
}

export function SaveFeishuConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveFeishuConfig'](arg1, arg2);
}

export function SaveMemoryFileContent(arg1, arg2) {
  return window['go']['app']['App']['SaveMemoryFileContent'](arg1, arg2);
}

export function SearchMemory(arg1, arg2) {
  return window['go']['app']['App']['SearchMemory'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetVaultEntry(arg1, arg2) {
  return window['go']['app']['App']['SetVaultEntry'](arg1, arg2);
}

export function StartOAuthLogin(arg1) {
  return window['go']['app']['App']['StartOAuthLogin'](arg1);
}

export function SyncMemory() {
  return window['go']['app']['App']['SyncMemory']();
}

export function TestChannelConnection(arg1) {
  return window['go']['app']['App']['TestChannelConnection'](arg1);
}

export function TestProviderConnection(arg1) {
  return window['go']['app']['App']['TestProviderConnection'](arg1);
}

export function ToggleCronJob(arg1, arg2) {
  return window['go']['app']['App']['ToggleCronJob'](arg1, arg2);
}

export function TriggerCronJob(arg1) {
  return window['go']['app']['App']['TriggerCronJob'](arg1);
}

export function UpdateCronJob(arg1) {
  return window['go']['app']['App']['UpdateCronJob'](arg1);
}

export function WriteCanvasFile(arg1, arg2) {
  return window['go']['app']['App']['WriteCanvasFile'](arg1, arg2);
}
