// Auto-generated Wails bindings shim for app.App.
// The real version is generated by `wails dev` / `wails build`.
// This shim delegates to window.go.app.App.* via the Wails JS bridge.

import { callGo } from "../../runtime/runtime";

// Wails v2 bridge path: window.go["app"]["App"]["<Method>"]
const PKG = "app";
const STRUCT = "App";

export interface ProviderInfo {
  id: string;
  type: string;
  hasKey: boolean;
}

export interface ChannelInfo {
  name: string;
  provider: string;
  model: string;
  sessions: number;
}

export interface AgentConfig {
  name: string;
  provider: string;
  model: string;
  system_prompt: string;
  max_tokens: number;
  tools?: string[];
  skill_paths?: string[];
}

export interface WhipflowConfig {
  default_provider?: string;
  cli_providers?: Record<string, {
    name?: string;
    bin?: string;
    prompt_mode?: string;
    args?: string[];
    stdin_args?: string[];
    timeout?: number;
    output_format?: string;
    raw_prompt?: boolean;
  }>;
}

export interface Config {
  providers: Record<string, { type: string; api_key: string; base_url: string }>;
  agents: AgentConfig[];
  default_agent: string;
  whipflow?: WhipflowConfig;
}

export interface HistoryMessage {
  role: string;
  content: string;
}

export interface VaultEntry {
  key: string;
  value: string;
  updated_at: number;
}

export const GetVault = (): Promise<VaultEntry[]> =>
  callGo<VaultEntry[]>(PKG, STRUCT, "GetVault");

export const SetVaultEntry = (key: string, value: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "SetVaultEntry", key, value);

export const DeleteVaultEntry = (key: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "DeleteVaultEntry", key);

export const TriggerCronJob = (jobID: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "TriggerCronJob", jobID);

export const ListCanvasFiles = (): Promise<string[]> =>
  callGo<string[]>(PKG, STRUCT, "ListCanvasFiles");

export const ReadCanvasFile = (name: string): Promise<string> =>
  callGo<string>(PKG, STRUCT, "ReadCanvasFile", name);

export const WriteCanvasFile = (name: string, content: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "WriteCanvasFile", name, content);

export const IsFirstRun = (): Promise<boolean> =>
  callGo<boolean>(PKG, STRUCT, "IsFirstRun");

export const GetConfig = (): Promise<Config> =>
  callGo<Config>(PKG, STRUCT, "GetConfig");

export const SaveConfig = (cfg: Config): Promise<void> =>
  callGo<void>(PKG, STRUCT, "SaveConfig", cfg);

export const GetProviders = (): Promise<ProviderInfo[]> =>
  callGo<ProviderInfo[]>(PKG, STRUCT, "GetProviders");

export const SaveAPIKey = (providerID: string, key: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "SaveAPIKey", providerID, key);

export const StartOAuthLogin = (providerID: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "StartOAuthLogin", providerID);

export const GetModels = (providerID: string): Promise<string[]> =>
  callGo<string[]>(PKG, STRUCT, "GetModels", providerID);

export const TestProviderConnection = (providerID: string): Promise<boolean> =>
  callGo<boolean>(PKG, STRUCT, "TestProviderConnection", providerID);

export const GetChannels = (): Promise<ChannelInfo[]> =>
  callGo<ChannelInfo[]>(PKG, STRUCT, "GetChannels");

export const SaveChannelConfig = (ac: AgentConfig): Promise<void> =>
  callGo<void>(PKG, STRUCT, "SaveChannelConfig", ac);

export const DeleteChannelConfig = (name: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "DeleteChannelConfig", name);

export const TestChannelConnection = (name: string): Promise<boolean> =>
  callGo<boolean>(PKG, STRUCT, "TestChannelConnection", name);

export const SendMessage = (
  agentName: string,
  sessionID: string,
  content: string
): Promise<void> => callGo<void>(PKG, STRUCT, "SendMessage", agentName, sessionID, content);

export const AbortCurrentTurn = (
  agentName: string,
  sessionID: string
): Promise<void> => callGo<void>(PKG, STRUCT, "AbortCurrentTurn", agentName, sessionID);

export const GetHistory = (
  channelID: string,
  userID: string
): Promise<HistoryMessage[]> =>
  callGo<HistoryMessage[]>(PKG, STRUCT, "GetHistory", channelID, userID);

export const GetVersion = (): Promise<string> =>
  callGo<string>(PKG, STRUCT, "GetVersion");

export const OpenLogsFolder = (): Promise<void> =>
  callGo<void>(PKG, STRUCT, "OpenLogsFolder");

export const OpenWhipflowSession = (
  toolExecID: string,
  sessionIndex: number,
  agentName: string
): Promise<Record<string, string>> =>
  callGo<Record<string, string>>(PKG, STRUCT, "OpenWhipflowSession", toolExecID, sessionIndex, agentName);

export const GetWebhookBaseURL = (): Promise<string> =>
  callGo<string>(PKG, STRUCT, "GetWebhookBaseURL");

export const GetChatSessions = (agentName: string): Promise<string[]> =>
  callGo<string[]>(PKG, STRUCT, "GetChatSessions", agentName);

export const GetFeishuConfig = (): Promise<Record<string, string>> =>
  callGo<Record<string, string>>(PKG, STRUCT, "GetFeishuConfig");

export const SaveFeishuConfig = (appID: string, appSecret: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "SaveFeishuConfig", appID, appSecret);

export const GetWhatsAppStatus = (): Promise<string> =>
  callGo<string>(PKG, STRUCT, "GetWhatsAppStatus");

export const GetWhatsAppQR = (): Promise<string> =>
  callGo<string>(PKG, STRUCT, "GetWhatsAppQR");

export const LogoutWhatsApp = (): Promise<void> =>
  callGo<void>(PKG, STRUCT, "LogoutWhatsApp");

// ─── Config Raw ──────────────────────────────────────────────────────────────

export const GetConfigRaw = (): Promise<Record<string, string>> =>
  callGo<Record<string, string>>(PKG, STRUCT, "GetConfigRaw");

export const SaveConfigRaw = (content: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "SaveConfigRaw", content);

// ─── Tool Executions ──────────────────────────────────────────────────────────

export interface ToolExecutionInfo {
  id: string;
  name: string;
  args?: Record<string, unknown>;
  result?: string;
  isError: boolean;
  timestamp: number;
  partialSteps?: any[];
  status?: string; // "running" | "done" | "error" | "interrupted"
  startedAt?: number;
  endedAt?: number;
}

export const GetToolExecutions = (
  channelID: string,
  userID: string
): Promise<ToolExecutionInfo[]> =>
  callGo<ToolExecutionInfo[]>(PKG, STRUCT, "GetToolExecutions", channelID, userID);

export const GetToolExecutionState = (
  channelID: string,
  userID: string
): Promise<ToolExecutionInfo[]> =>
  callGo<ToolExecutionInfo[]>(PKG, STRUCT, "GetToolExecutionState", channelID, userID);

// ─── Skills ───────────────────────────────────────────────────────────────────

export interface SkillInfo {
  name: string;
  description: string;
  filePath: string;
  source: string;
}

export const GetAllSkills = (): Promise<SkillInfo[]> =>
  callGo<SkillInfo[]>(PKG, STRUCT, "GetAllSkills");

export const GetSkillContent = (filePath: string): Promise<string> =>
  callGo<string>(PKG, STRUCT, "GetSkillContent", filePath);

export const GetAgentSkills = (agentName: string): Promise<SkillInfo[]> =>
  callGo<SkillInfo[]>(PKG, STRUCT, "GetAgentSkills", agentName);

export const AddSkillPath = (agentName: string, path: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "AddSkillPath", agentName, path);

export const RemoveSkillPath = (agentName: string, path: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "RemoveSkillPath", agentName, path);

export interface RemoteSkillInfo {
  name: string;
  version: string;
  description: string;
  author: string;
  downloads: number;
}

export const SearchRemoteSkills = (query: string): Promise<RemoteSkillInfo[]> =>
  callGo<RemoteSkillInfo[]>(PKG, STRUCT, "SearchRemoteSkills", query);

export const InstallRemoteSkill = (name: string, sync: boolean): Promise<string> =>
  callGo<string>(PKG, STRUCT, "InstallRemoteSkill", name, sync);

// ─── Cron Jobs ──────────────────────────────────────────────────────────────

export interface ScheduleData {
  at?: string;
  everyMs?: number;
  anchorMs?: number;
  expr?: string;
  tz?: string;
}

export interface CronJob {
  id: string;
  name: string;
  scheduleKind: string; // "at" | "every" | "cron"
  schedule: ScheduleData;
  agentName: string;
  prompt: string;
  enabled: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface CronJobHistory {
  id: number;
  jobId: string;
  startedAt: string;
  finishedAt?: string;
  status: string; // "running" | "success" | "error"
  resultText: string;
  errorText: string;
}

export const ListCronJobs = (): Promise<CronJob[]> =>
  callGo<CronJob[]>(PKG, STRUCT, "ListCronJobs");

export const AddCronJob = (job: CronJob): Promise<void> =>
  callGo<void>(PKG, STRUCT, "AddCronJob", job);

export const UpdateCronJob = (job: CronJob): Promise<void> =>
  callGo<void>(PKG, STRUCT, "UpdateCronJob", job);

export const DeleteCronJob = (jobID: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "DeleteCronJob", jobID);

export const ToggleCronJob = (jobID: string, enabled: boolean): Promise<void> =>
  callGo<void>(PKG, STRUCT, "ToggleCronJob", jobID, enabled);

export const GetCronJobHistory = (
  jobID: string,
  limit: number
): Promise<CronJobHistory[]> =>
  callGo<CronJobHistory[]>(PKG, STRUCT, "GetCronJobHistory", jobID, limit);

export const GetCronJobHistoryAll = (limit: number): Promise<CronJobHistory[]> =>
  callGo<CronJobHistory[]>(PKG, STRUCT, "GetCronJobHistoryAll", limit);

// ─── Memory ───────────────────────────────────────────────────────────────────

export interface MemoryFile {
  path: string;
  name: string;
  hash: string;
  modifiedAt: number;
  indexedAt: number;
  chunkCount: number;
}

export interface MemorySearchResult {
  filePath: string;
  startLine: number;
  endLine: number;
  content: string;
  score: number;
}

export const ListMemoryFiles = (): Promise<MemoryFile[]> =>
  callGo<MemoryFile[]>(PKG, STRUCT, "ListMemoryFiles");

export const GetMemoryFileContent = (path: string): Promise<string> =>
  callGo<string>(PKG, STRUCT, "GetMemoryFileContent", path);

export const SaveMemoryFileContent = (path: string, content: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "SaveMemoryFileContent", path, content);

export const DeleteMemoryFile = (path: string): Promise<void> =>
  callGo<void>(PKG, STRUCT, "DeleteMemoryFile", path);

export const CreateMemoryFile = (name: string): Promise<string> =>
  callGo<string>(PKG, STRUCT, "CreateMemoryFile", name);

export const SearchMemory = (query: string, limit: number): Promise<MemorySearchResult[]> =>
  callGo<MemorySearchResult[]>(PKG, STRUCT, "SearchMemory", query, limit);

export const SyncMemory = (): Promise<void> =>
  callGo<void>(PKG, STRUCT, "SyncMemory");

export const GetMemoryDir = (): Promise<string> =>
  callGo<string>(PKG, STRUCT, "GetMemoryDir");

export const ListWhipFiles = (): Promise<string[]> =>
  callGo<string[]>(PKG, STRUCT, "ListWhipFiles");

export const GetWhipFileContent = (path: string): Promise<string> =>
  callGo<string>(PKG, STRUCT, "GetWhipFileContent", path);

// ─── Browser (CDP) ──────────────────────────────────────────────────────────

export interface BrowserStatus {
  connected: boolean;
  cdpURL: string;
  browser: string;
  error: string;
}

export const BrowserTestCDP = (): Promise<BrowserStatus> =>
  callGo<BrowserStatus>(PKG, STRUCT, "BrowserTestCDP");

export const BrowserLaunchChrome = (): Promise<BrowserStatus> =>
  callGo<BrowserStatus>(PKG, STRUCT, "BrowserLaunchChrome");

export interface ShortcutInfo {
  platform: string;
  file: string;
  commands: string[];
}

export const BrowserListShortcuts = (): Promise<ShortcutInfo[]> =>
  callGo<ShortcutInfo[]>(PKG, STRUCT, "BrowserListShortcuts");

export const BrowserRunShortcut = (file: string, command: string, args: string[]): Promise<Record<string, unknown>[]> =>
  callGo<Record<string, unknown>[]>(PKG, STRUCT, "BrowserRunShortcut", file, command, args);

// ─── Remote Control ──────────────────────────────────────────────────────────

export interface RemoteStatus {
  enabled: boolean;
  lanUrl: string;
  ngrokUrl: string;
  qrCode: string;
  token: string;
  port: number;
  lanIP: string;
  ngrokOn: boolean;
  clients: number;
}

export const EnableRemote = (): Promise<RemoteStatus> =>
  callGo<RemoteStatus>(PKG, STRUCT, "EnableRemote");

export const DisableRemote = (): Promise<void> =>
  callGo<void>(PKG, STRUCT, "DisableRemote");

export const EnableNgrok = (authToken: string): Promise<RemoteStatus> =>
  callGo<RemoteStatus>(PKG, STRUCT, "EnableNgrok", authToken);

export const DisableNgrok = (): Promise<void> =>
  callGo<void>(PKG, STRUCT, "DisableNgrok");

export const GetRemoteStatus = (): Promise<RemoteStatus> =>
  callGo<RemoteStatus>(PKG, STRUCT, "GetRemoteStatus");
